apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - issuer/selfsigned.yaml
  - edge/ingress.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/hpa.yaml
  - db/statefulset.yaml
  - rbac/rbac.yaml
  - netpol/networkpolicies.yaml